### ISSUE TITLE
Facing problem with APIKey decoding

### ISSUE THREAD

**Issue by rohitswarke** [willblaschko/AlexaAndroid#13]
Hi Will,

Thank you for sharing this. Great Job.
I'm facing some difficulty while running this app in my android studio. I crossed check your given instructions couple of times but don't know what I'm missing. The problem is with APIKey decoding.
Can you please help me with this.

Thanks!
RohitW
`
06-20 18:08:15.035 9975-9975/com.willblaschko.android.alexavoicelibrary W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Failed to decode: Decoding failed: certificate fingerprint can't be verified! pkg=com.willblaschko.android.alexavoicelibrary
06-20 18:08:15.035 9975-9975/com.willblaschko.android.alexavoicelibrary W/com.amazon.identity.auth.device.appid.APIKeyDecoder: Unable to decode APIKey for pkg=com.willblaschko.android.alexavoicelibrary
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler: Unable to Use Amazon Authorization Manager. APIKey is incorrect or does not exist. Does assets/api_key.txt exist in the main application?
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler: java.lang.IllegalArgumentException: Invalid API Key
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at com.amazon.identity.auth.device.authorization.api.AmazonAuthorizationManager.<init>(AmazonAuthorizationManager.java:133)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at com.willblaschko.android.alexa.AuthorizationManager.<init>(AuthorizationManager.java:55)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at com.willblaschko.android.alexa.AlexaManager.<init>(AlexaManager.java:47)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at com.willblaschko.android.alexa.AlexaManager.getInstance(AlexaManager.java:53)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at com.willblaschko.android.alexavoicelibrary.BaseActivity.initAlexaAndroid(BaseActivity.java:98)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at com.willblaschko.android.alexavoicelibrary.BaseActivity.onCreate(BaseActivity.java:65)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at com.willblaschko.android.alexavoicelibrary.MainActivity.onCreate(MainActivity.java:30)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at android.app.Activity.performCreate(Activity.java:6010)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at android.app.ActivityThread.access$800(ActivityThread.java:155)
06-20 18:08:15.037 9975-9975/com.willblaschko.android.alexavoicelibrary E/AuthorizationHandler:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
`

**Comment by willblaschko** [comment]
So two things:
- You should change the app package name to something else, otherwise it won't run.
- You need to go to the [Dashboard](https://developer.amazon.com/edw/home.html#/avs/list), create a new product and security profile for it. Under Security Profile for your new product, you'll have a tab called Amazon/Kindle. Copy that string exactly into a file you add to the project under main/assets called "api_key.txt"

You can use this [utility method](https://github.com/willblaschko/AlexaAndroid/blob/master/libs/AlexaAndroid/src/main/java/com/willblaschko/android/alexa/utility/SigningKey.java) to get your MD5 fingerprint for the security profile.

**Comment by rohitswarke** [comment]
Thanks Will for looking into my issue. I tried solutions given by you but not succeeded in running the code. I'll now give a fresh try to all the steps once again.
Thanks for your help!
Cheers!
--Rohit

**Comment by willblaschko** [comment]
@rohitswarke have you had any luck?

**Comment by rohitswarke** [comment]
sorry for late reply. Broken wrist :-{ so away from computer. I'll give it a try when I get recovered.
Thanks!

**Comment by willblaschko** [comment]
Closing, please reopen if you continue to have issues.

**Comment by amiga** [comment]
so we cannot use com.willblaschko.android.alexavoicelibrary  ? we must refactor it right ?

**Comment by TroubleKid** [comment]
Hi Will,

I am very fortunate to find this project. It helps me a lot.Thanks.
But I still have many problems with my Alexa development，so I ask for your help.
First of all, I 'm puzzled about the Authorization API, I found that you called the method authorize(String[] scopes, Bundle options, AuthorizationListener listener) to authorize, but this method is  deprecated now and it's not the same as the sample code on https://developer.amazon.com/docs/alexa-voice-service/authorize-on-product.html, I visited Amazon Developer Forums and I found the developers all called the same method as you, and I couldn't find any sample code and document about this API, I'm confused.
I don't know if the official API is changed. Some methods have been replaced.
And I'm not sure if HTTP/2 connection is the only way I can interact with alexa? I mean if there is a official package so that I only need call some methods?

**Comment by Gmrevo** [comment]
@amiga @rohitswarke Did you guys had any success in solving the error? I am facing the same error for invalid API key even after following the steps. Can anyone please share the solution. 
Great work @willblaschko . 
Please find the screenshot in support.
![screenshot from 2018-04-27 16-15-39](https://user-images.githubusercontent.com/11976260/39359118-4d86cab0-4a36-11e8-9fa3-ae09e2173ca0.png)
