### ISSUE TITLE
Alexa library Support for Linux.

### ISSUE THREAD

**Issue by rahuljeyaraj** [willblaschko/AlexaAndroid#16]
Does your Alexa library can be used for Linux Platform also? If yes what is the changes we need to do.
? Any suggestion would be of great help.

**Comment by willblaschko** [comment]
At very least you could go through the code and see how I'm doing all the connections and parsing, the library, as a whole, can't be dropped into Linux because there are some Android-specific implementations: OkHttp (I believe is Android-only), as well as some other calls like TextUtils.equals() which are part of Android's library.

The code itself is not that complicated, there are just a lot of little pieces, so porting it over to another language/platform would mostly just require a networking library with similar capabilities.

**Comment by rahuljeyaraj** [comment]
Any idea how to do authentication for Linux as I can see for authentication "LoginwithAmazonSdk.jar" is used which launches activity with WebView. Do you know how to do authentication for Linux platform?

**Comment by willblaschko** [comment]
Amazon has a couple different binaries they distribute based on the platform, they're available in the documentation for the Alexa service. If you're trying to design a headless unit, you can use a secondary device to pass in the auth code.

To start, I'd take a look here:
https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/authorizing-your-alexa-enabled-mobile-app

and

https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/authorizing-your-alexa-enabled-mobile-app
