### ISSUE TITLE
[Question]About OKHttp 'the Connection Reset By Peer' issue

### ISSUE THREAD

**Issue by nezen** [willblaschko/AlexaAndroid#32]
Thanks for your awesome work! I noticed this comment from your code: 
/**
 * Create a singleton OkHttp client that, hopefully, will someday be able to make sure all connections are valid according to AVS's strict
 * security policy--this will hopefully fix the Connection Reset By Peer issue.
 *
 * Created by willb_000 on 6/26/2016.
 */

So when does this problem happen? what's the consequences of OKHttp **Connection Reset By Peer** issue?  Amazon recommends three http2 library: OKHTTP, Jetty and Netty. If it's a severe problem,  should I consider using an alternate? How can I make sure the other 2 libs do not have same issue?

appreciate your suggestion.

**Comment by willblaschko** [comment]
The issue is that older Android devices don't support http2 (specifically the tls 1.2 protocol), so even though I'm using OkHttp, they're unable to make the secure connection, so it gets dropped. This will likely be true no matter which library you use.

I was trying (as shown in the comment), unsuccessfully, to find a workaround for the issue for older devices. Unfortunately a lot of devices are affected by this, including some that have since been upgraded to Android 6.0 (thanks Samsung).

I'm still thinking about options, but I haven't found anything that I feel will work.

**Comment by nezen** [comment]
Get it and Thanks!
