### ISSUE TITLE
Could not find property 'releaseConfig' on SigningConfig container

### ISSUE THREAD

**Issue by rajashekar2012** [willblaschko/AlexaAndroid#33]
Hi,
i'm new to both java and android.I'm trying to run this sample code.Getting this error while building 
" Could not find property 'releaseConfig' on SigningConfig container"  in build.gradle file (using windows 10)

**Comment by amitks2015** [comment]
You need to sign your application first.
https://developer.android.com/studio/publish/app-signing.html
Then register your application to amazon and generate api key.
http://login.amazon.com/android

**Comment by willblaschko** [comment]
Like @amitks2015 said, you will need to use your own signing configuration for your app. I didn't include my key and signing config because I used them to put the sample app in the store.

Update the build.gradle with your own configuration, use that for the Amazon API, and you should be good to go :)

**Comment by rajashekar2012** [comment]
thanks for the reply , but when i sign my app i'm getting the following error
[stack overflow](http://stackoverflow.com/questions/39534634/could-not-find-method-android-for-arguments-error-while-building-in-android-st)
