### ISSUE TITLE
I met error in android 4.4.4 "System.err: javax.net.ssl.SSLException: Connection closed by peer "

### ISSUE THREAD

**Issue by chenhequn** [willblaschko/AlexaAndroid#34]
System.err: javax.net.ssl.SSLException: Connection closed by peer                                                       
System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)                               
System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)               
System.err:     at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)                               
System.err:     at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)

**Comment by willblaschko** [comment]
Because AVS requires TLS 1.2, with a limited set of cipher suites, and HTTP/2, older versions of Android often aren't supported. You start seeing full support with Android 5.0.

One option would be to refactor the library to use Netty instead of OkHttp--since OkHttp only supports HTTP/2 from 5.0 onward (as far as I can tell), but that's not a task I've wanted to tackle, yet.
