### ISSUE TITLE
'com.google.android.gms:play-services:9.4.+' whole api needed? 

### ISSUE THREAD

**Issue by sindaco09** [willblaschko/AlexaAndroid#40]
In the AlexaAndroid/libs/AlexaAndroid/build.gradle file I noticed you include the entire Google play-services api. is it possible for you to reduce this to only the play-service API's needed? I suspect this dependency is causing the need for multidex (as it has caused for me in the past). I noticed this when I was adding Firebase to my project and it informed me that i had duplicates. Otherwise great job on this library, really useful!

https://developers.google.com/android/guides/setup

**Comment by willblaschko** [comment]
It's required for the updated cipher suites for older devices, I didn't see a sub-package that had the [ProviderInstaller](https://developers.google.com/android/reference/com/google/android/gms/security/ProviderInstaller) classes, if you find one, I'd be happy to swap it out--I don't really like having the whole thing in there, either. I thought about removing it and just keeping previous compatibility, mostly because I'm not sure how much of a difference it'll make.

**Comment by willblaschko** [comment]
You can also do something like this: https://www.linkedin.com/pulse/how-find-dependencies-particular-dependency-gradle-hesamedin-kamalan-1

**Comment by sindaco09** [comment]
I believe i found the sub-directory, wasn't very intuitive but I swapped out:
    compile 'com.google.android.gms:play-services:9.4.+'
with 
    compile 'com.google.android.gms:play-services-base:9.4.+'
also google play services version 9.6.1 is available, not sure if 9.4 is for compatibility reasons

**Comment by willblaschko** [comment]
Great! No reason to not upgrade to 9.6.1, just that's what I had when I put it together a few weeks back. If you want to put a pull request up, I'd be happy to merge in the change, I'm sure everyone would appreciate it. Otherwise, I probably can get to it this weekend.
