### ISSUE TITLE
How to receive StopCapture Directive

### ISSUE THREAD

**Issue by skypiri** [willblaschko/AlexaAndroid#47]
First of all, thanks for your sharing your code. 
I found that there are 3 kinds of ASR profile (CLOSE_TALK, NEAR_FIELD, FAR_FIELD).
And I can receive StopCapture directive from Alexa when I use a profile near_field or far_field.
So I modify SpeechRecognizer event from close_talk to near or far and remove the code that determines end of speech at client. (I guess that is recorder.isPausing())
After that, I run the program. but I can't any directives to stop recording. How can I receive that directive?

**Comment by orafaaraujo** [comment]
I'm facing the same problem.

Any ideias, @skypiri or @willblaschko ?

Thanks!

**Comment by willblaschko** [comment]
Just pushed a ton of updates including a DownChannel to support StopCapture. I haven't created a new Maven version yet because I want a chance to polish what I just wrote and do some much-needed refactoring once I've considered the code.

The latest version of Alexa Listens supports this if you want to see it in action.

The basics are here, for the moment: https://github.com/willblaschko/AlexaAndroid/blob/master/libs/AlexaAndroid/src/main/java/com/willblaschko/android/alexa/service/DownChannelService.java

I added an EventBus and changed the default to NEAR_FIELD (it performed better than FAR_FIELD in my testing), so add a listener on there wherever you're listening for StopCapture, either for AvsItem or AvsStepCaptureItem
