### ISSUE TITLE
How can i play other app`s music??

### ISSUE THREAD

**Issue by figodxp** [willblaschko/AlexaAndroid#72]
Hello
I just want to know that could play music from other app`s music with your sample, like voice assistance in google phone play google player music???
If so how can i do?

**Comment by willblaschko** [comment]
Google is able to do that because it has a tighter integration with its own ecosystem than this. Theoretically you could design a companion skill that sends a push notification to the phone to start an app that supports deeplinking.

"Ask My Skill to play Lindsey Stirling on Pandora" > Skill processes "Lindsey Stirling" and "Pandora > sends a push notification to the app that just sent the AVS request > app uses a deep link intent to launch Pandora playing Lindsey Stirling.

This is essentially what Google is doing, just they have the ability at a 1p level instead of a 3p invoked skill.
