### ISSUE TITLE
Card response?

### ISSUE THREAD

**Issue by ericwjr** [willblaschko/AlexaAndroid#73]
Is it possible to get the card response using AVS?  Is it possible to get the session attributes?  So far it looks like we are not able to get any of the response that comes from the back-end lambda function only the reply audio.

I don't see anything in ResponseParser that would suggest that it can.

**Comment by willblaschko** [comment]
AVS is audio-in and audio-out only (with a few other things that bleed over for voice control like play/pause/volume).

To the best of my knowledge, cards and session attributes are not available through the AVS service because this could pose a huge security risk for skills dealing with PII.

If you breakpoint inside ResponseParser and look at the return from AVS, you'll see that very little information is actually sent back for a request.

**Comment by ericwjr** [comment]
Ok thanks...I need something similar to the service simulator in Android where I can get the raw response back from back-end before it gets processed into speech
